services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://meloman_user:meloman_pass@db:5432/meloman_db
    depends_on:
      - db
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    environment:
      - HOST=0.0.0.0
    restart: always

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: meloman_user
      POSTGRES_PASSWORD: meloman_pass
      POSTGRES_DB: meloman_db
    restart: always

volumes:
  pgdata:
