version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 4780
      POSTGRES_DB: pochta_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pochta_network  

  web:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:4780@db/pochta_db
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    command: python app.py
    networks:
      - pochta_network

networks:
  pochta_network:
    driver: bridge

volumes:
  postgres_data:
