"""catalog add year/album/lyrics

Revision ID: 64ad7e127bc6
Revises: 1af02f1012ca
Create Date: 2025-08-21 06:12:14.008276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64ad7e127bc6'
down_revision = '1af02f1012ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catalog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('album', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('lyrics', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catalog', schema=None) as batch_op:
        batch_op.drop_column('lyrics')
        batch_op.drop_column('album')
        batch_op.drop_column('year')

    # ### end Alembic commands ###
